.TH "md___users_guilhermemorais__c_lion_projects_trab1-icc__r_e_a_d_m_e" 3 "Thu Oct 24 2019" "Version v2.1" "PDE Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_guilhermemorais__c_lion_projects_trab1-icc__r_e_a_d_m_e \- Partial Differential Equation Solver 
A program to find an approximate solution to a Partial Differential Equation (PDE) using the Gauss-Seidel iterative method to solve the pentadiagonal matrix that represents the Linear System found with the aproximation of the partial derivatives of the equation\&. 
