.TH "/Users/guilhermemorais/CLionProjects/trab1-icc/README.md" 3 "Thu Oct 24 2019" "Version v2.1" "PDE Solver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/guilhermemorais/CLionProjects/trab1-icc/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for PDE Solver from the source code\&.
